name: Lint and Prettier Check

on:
  pull_request:
    branches: 
      - "master"
  push:
    branches: 
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npm run lint

      # stop workflow on fail
      - name: Fail on lint errors
        if: failure()
        run: exit 1

  # push to GitHub
  fix:
    runs-on: ubuntu-latest
    needs: lint  # Run this job only if linting passes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Run Prettier
      - name: Run Prettier (auto-fix)
        run: npx prettier --write .

      # Run ESLint
      - name: Run ESLint (auto-fix)
        run: npm run lint:fix

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Apply Prettier and ESLint fixes" || echo "No changes to commit"
          git push
