name: Run E2E Tests Docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
        with:
          repository: DWintermans/BlackjackRoyale_Frontend
          ref: master
          path: frontend

      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          repository: DWintermans/BlackjackRoyale
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          path: backend 
          
      - name: Checkout docker folder
        uses: actions/checkout@v3
        with:
          repository: DWintermans/BlackjackRoyale_Docker
          ref: main
          path: docker 
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
      - name: Build and start services
        working-directory: ./docker
        run: |
          docker-compose -f docker-compose.yml up -d --build  

      - name: Wait for all services to become healthy
        working-directory: ./docker
        run: |
          echo "Waiting for all services to become healthy..."
          timeout 120s bash -c '
          while ! (docker-compose ps | grep -q "healthy"); do
            echo "Services not healthy yet, waiting..."
            sleep 5
          done
          echo "All services are healthy!"
          '

      - name: Run Cypress E2E tests
        working-directory: ./docker
        run: |
          docker-compose exec -T cypress cypress run --config-file /frontend/cypress/e2e/cypress.config.js 

      - name: Tear down services
        working-directory: ./docker
        run: |
          docker-compose down  
