name: Run E2E Tests Docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          repository: DWintermans/BlackjackRoyale
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          
      - name: Checkout docker folder
        uses: actions/checkout@v3
        with:
          repository: DWintermans/BlackjackRoyale_Docker
          ref: main
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up -d --build  

      - name: Wait for services to be ready
        run: |
          docker-compose exec -T api wait-for-it.sh api:8080 --timeout=30 
          docker-compose exec -T websocket wait-for-it.sh websocket:5000 --timeout=30  
          docker-compose exec -T db wait-for-it.sh db:3306 --timeout=30  

      - name: Run Cypress E2E tests
        run: |
          docker-compose exec -T cypress cypress run --config-file /cypress/e2e/cypress.config.js 

      - name: Tear down services
        run: |
          docker-compose down  
